# Gems used
gems:
  - octopress-minify-html
  - jekyll-paginate
  - jekyll-paginate-categories
  # - octopress-paginate

# Site info
name: Renormalized
description: Physics, music, tech, and much more
version: v0.0

# Build settings
source: src
destination: dist
env: production

# Set sass config
sass:
  sass_dir: _sass
  style: :compressed # Compressed css

# Collections
collections:
  music-review:
    output: false
    permalink: /:collection/:path/:name:output_ext

# Pagination settings
paginate: 5
paginate_path: "page:num"

# category_dir: "categories"
# category_layout: "index.html"

paginate_category_basepath: '/:name/'
paginate_category_layout: 'categories.html'
